spring:
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5433/polardb_order
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5433/polardb_order
    baseline-on-migrate: true

  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888/
server:
  shutdown: graceful
  netty:
    connection-timeout: 2s
  port: 9002
polar:
  catalog-service-url: http://localhost:9001
  greeting: Welcome to the Order Service!
